# Конфигурация для spring + (в перспективе) postgresql

version: '3.9'
services:
  app-ktor:
    image: ok-marketplace-app-ktor:0.0.1
    ports:
      - "8080:8080"
    environment:
      DB_TYPE_PROD: "cassandra"
      MKPLADS_HOST: "cassandra"
      MKPLADS_PORT: 9042
      MKPLADS_KEYSPACE: "marketplace_ads"
      MKPLADS_USER: "cassandra"
      MKPLADS_PASS: "cassandra"
      MKPLADS_LOGGER: "kmp"
    depends_on:
      cassandra:
        condition: service_healthy

  cassandra:
    image: cassandra:5.0.2
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./volumes/cassandra/cassandra.yaml:/opt/cassandra/conf/cassandra.yaml

#  liquibase:
#    image: liquibase/liquibase
#    volumes:
#      - ./volumes/liquibase-psql:/liquibase/changelog
#    depends_on:
#      psql:
#        condition: service_healthy
#    command: ["--defaults-file=/liquibase/changelog/liquibase.properties", "--search-path=/liquibase/changelog", "--url=jdbc:postgresql://psql:5432/marketplace_ads", "update"]
